[package]
name = "toph"
version = "0.11.0"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "An HTML generation library"
repository = "https://github.com/eze-works/toph"
categories = ["template-engine"]

keywords = ["template", "html"]
