// This crate only allows url values with the following schemes
pub const ALLOWED_URL_SCHEMES: [&str; 8] = [
    "http", "https", "mailto", "tel", "callto", "sms", "cid", "xmpp",
];

// List of attributes that require url encoding
pub const URL_ATTRIBUTES: [&str; 7] = [
    "action",
    "cite",
    "data",
    "formaction",
    "href",
    "poster",
    "src",
];

// This crate only allows setting values on attributes that are considered "safe sinks". These
// attributes treat their values as text and do not execute them. This excludes all the `on*` event
// handlers.
//
// It also omits attributes with types that can't be escaped with current crate functions (e.g.
// itemid which is a list of urls)
//
// The full list of attributes can be found here:
// https://html.spec.whatwg.org/multipage/indices.html#attributes-3
pub const ALLOWED_ATTR_NAMES: [&str; 123] = [
    "abbr",
    "accept",
    "accept-charset",
    "accesskey",
    "action",
    "allow",
    "allowfullscreen",
    "alt",
    "as",
    "async",
    "autocapitalize",
    "autocomplete",
    "autofocus",
    "autoplay",
    "blocking",
    "charset",
    "checked",
    "cite",
    "class",
    "color",
    "cols",
    "colspan",
    "content",
    "contenteditable",
    "controls",
    "coords",
    "crossorigin",
    "data",
    "datetime",
    "decoding",
    "default",
    "defer",
    "dir",
    "dirname",
    "disabled",
    "download",
    "draggable",
    "enctype",
    "enterkeyhint",
    "fetchpriority",
    "for",
    "form",
    "formaction",
    "formenctype",
    "formmethod",
    "formnovalidate",
    "formtarget",
    "headers",
    "height",
    "hidden",
    "high",
    "href",
    "hreflang",
    "http-equiv",
    "id",
    "imagesizes",
    "imagesrcset",
    "inert",
    "inputmode",
    "integrity",
    "is",
    "ismap",
    // microdata item* not supported
    "kind",
    "label",
    "lang",
    "list",
    "loading",
    "loop",
    "low",
    "max",
    "maxlength",
    "media",
    "method",
    "min",
    "minlength",
    "multiple",
    "muted",
    "name",
    "nomodule",
    "nonce",
    "novalidate",
    "open",
    "optimum",
    "pattern",
    // ping: space seperated urls not yet supported
    "placeholder",
    "playsinline",
    "popover",
    "popovertarget",
    "popovertargetaction",
    "poster",
    "preload",
    "readonly",
    "referrerpolicy",
    "rel",
    "required",
    "reversed",
    "rows",
    "rowspan",
    "sandbox",
    "scope",
    "selected",
    "shadowrootmode",
    "shadowrootdelegatesfocus",
    "shadowrootclonable",
    "shape",
    "size",
    "sizes",
    "slot",
    "span",
    "spellcheck",
    "src",
    "srcdoc",
    "srclang",
    "srcset",
    "start",
    "step",
    // "style" Be explicit about setting style using the attr! macro
    "tabindex",
    "target",
    "title",
    "translate",
    "type",
    "usemap",
    "value",
];
